// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssetTreeCategory = { children: { [key in string]?: AssetTreeEntry }, };

export type AssetTreeEntry = { "type": "Asset" } | { "type": "Category" } & AssetTreeCategory;

export type ListAssetsResult = { assets: Array<string>, };

export type ListElementsResult = { elements: Array<string>, };

export type ListExportFormatsResult = { formats: Array<string>, };

export type ListShotsResult = { shots: Array<string>, };

export type SetupResult = { asset: string, department: string, path: string, file_name: string, shot: string | null, };

export type SummaryResponse = { display_name: string, identifier: string, assets_flat: Array<string>, departments: Array<string>, };
