// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SummaryResponse = { display_name: string, identifier: string, assets_flat: Array<string>, departments: Array<string>, };
