// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResolvedElementData = { shot_local: boolean, dependencies: Array<string> | null, asset: string | null, shot: string | null, owning_department: string | null, };
