// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedElementData } from "./ResolvedElementData";
import type { VersionControlFile } from "./VersionControlFile";

export type ResolvedElementResult = { info: ResolvedElementData, versions: Array<VersionControlFile>, };
