title: Conduct
description: A highly configurable pipeline for digital projects
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Source: https://github.com/lagmachinery/conduct
